sonar.projectKey=ravindu200232_food-ordering-order-service
sonar.organization=ravindu200232
sonar.projectName=Food Ordering - Order Service
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/node_modules/**,**/**tests**/**,**/coverage/**,**/Dockerfile,**/*.md

sonar.sources=src
sonar.tests=tests

sonar.exclusions=/node_modules/,/coverage/,/Dockerfile,/.md
sonar.test.inclusions=**/.test.js

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8