sonar.projectKey=ravindu200232_food-ordering-user-service
sonar.organization=ravindu200232
sonar.projectName=Food Ordering - User Service
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/node_modules/**,**/**tests**/**,**/coverage/**,**/Dockerfile,**/*.md

sonar.tests=**tests**
sonar.test.inclusions=**/**tests**/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.language=js
